"""add_student_fields_and_user_cnic

Revision ID: 6b7fb0f10c43
Revises: 2a36fb7df209
Create Date: 2026-04-25 15:14:34.652084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6b7fb0f10c43'
down_revision: Union[str, None] = '2a36fb7df209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('roll_number', sa.String(length=50), nullable=True))
    op.add_column('students', sa.Column('photo_url', sa.String(length=500), nullable=True))
    op.add_column('students', sa.Column('qr_hash', sa.String(length=64), nullable=True))
    op.add_column('students', sa.Column('class_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('section_name', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('teacher_name', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('teacher_cnic', sa.String(length=20), nullable=True))
    op.alter_column('students', 'section_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_index(op.f('ix_students_qr_hash'), 'students', ['qr_hash'], unique=True)
    op.create_index(op.f('ix_students_teacher_cnic'), 'students', ['teacher_cnic'], unique=False)
    op.add_column('users', sa.Column('cnic', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'cnic')
    op.drop_index(op.f('ix_students_teacher_cnic'), table_name='students')
    op.drop_index(op.f('ix_students_qr_hash'), table_name='students')
    op.alter_column('students', 'section_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('students', 'teacher_cnic')
    op.drop_column('students', 'teacher_name')
    op.drop_column('students', 'section_name')
    op.drop_column('students', 'class_name')
    op.drop_column('students', 'qr_hash')
    op.drop_column('students', 'photo_url')
    op.drop_column('students', 'roll_number')
    # ### end Alembic commands ###
